version: '3'

services:
    app:
        build: .
        env_file: 
            - ./config.env
        command: ./main
        ports:
            - "8000:8000"
    neo4j:
        image: 'bitnami/neo4j:4'
        env_file: 
            - ./neo4j.env
        ports:
          - '7474:7474'
          - '7473:7473'
          - '7687:7687'
        volumes:
          - 'neo4j_data:/bitnami'
volumes:
    neo4j_data:
        driver: local
    