version: '3'

services:
    app:
        build: .
        env_file: 
            - ./settings.env
        command: ./main
        ports:
            - "8080:8080"
    neo4j:
        image: 'neo4j:3.5.14'
        ports:
          - '7474:7474'
          - '7473:7473'
          - '7687:7687'
        volumes:
          - /var/www/neo4j-data:/data
    