package models

import "github.com/neo4j/neo4j-go-driver/neo4j"

type summaryData struct {
	WithSymptoms int
	Positive     int
}

// ContactSummary gives details about health statuses of
// the user's primary and secondary connections
type ContactSummary struct {
	First  summaryData
	Second summaryData
}

func buildSummaryData(summary neo4j.Record, index string) summaryData {
	withSymptoms, _ := summary.Get(index + "WithSymptoms")
	positive, _ := summary.Get(index + "Positive")

	return summaryData{
		WithSymptoms: withSymptoms.(int),
		Positive:     positive.(int),
	}
}

// BuildContactSummary builds a ContactSummary from a neo4j record
// generated by the GetContactSummary query
func BuildContactSummary(summary neo4j.Record) ContactSummary {
	result := ContactSummary{
		First:  buildSummaryData(summary, "first"),
		Second: buildSummaryData(summary, "second"),
	}
	return result
}
